/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_mobile_analytics_app_id": "e9f07a53f6094b5c889243630b0b89d7",
    "aws_mobile_analytics_app_region": "ap-southeast-1",
    "aws_cloud_logic_custom": [
        {
            "name": "aceapi",
            "endpoint": "https://x477h82ll9.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ylcxo355x5gx7ceyvw6wf3oxfu.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kotdskf53rf2jfjpto6rm4dhcy",
    "aws_cognito_identity_pool_id": "ap-southeast-1:0d6e1cc7-d2bc-4608-b07e-ea55171a19f1",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_ghUaOj53i",
    "aws_user_pools_web_client_id": "2na8de6un2hfdtko1td9ngaelv",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
